### ISSUE TITLE
The display of the query content does not work.

### ISSUE THREAD

**Issue by vanopivovar** [mfoulks3200/har-analyzer#6] opened 2023-03-31 09:40 UTC
When I click on the line with the request, then in the right part of the VS Code (inspector) screen, the content of the request is not displayed.

(Maybe because the file size is 5687 kb?)

![2023-03-31_11-39-30](https://user-images.githubusercontent.com/56223840/229085289-aaf0162c-fa4a-4489-9cef-e93d76384368.png)

**Comment by Archenoth** [comment] 2023-09-12 21:31
I can confirm this issue with a ~350kb .har as well, so your filesize miiight not be the issue here!

(Tested on VSCode 1.82.0, Linux x64)

**Comment by Archenoth** [comment] 2023-09-13 00:20
So! It turns out the very last line of the function that runs when you click a HAR entry is the line that was responsible for unhiding the inspector, so any errors getting to that point would just cause it to fail to render

I made a single-character PR to (hopefully) fix that~

**Comment by ackermanusaa** [comment] 2023-12-14 20:51
Also encountering this issue

**Comment by mfoulks3200** [comment] 2023-12-15 01:07
Closing this issue, as the associated PR was accepted. Let me know if this issue continues happening.

**Closed as completed by mfoulks3200** 2023-12-15 01:07 UTC
